name: Java Maven Code Quality

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-deps-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-deps-${{ runner.os }}-

      - name: Pre-fetch Maven Dependencies
        run: mvn dependency:go-offline

      - name: Resolve Maven Plugin Dependencies
        run: mvn dependency:resolve-plugins

      - name: Run Maven Install without tests
        run: mvn clean install -DskipTests

      - name: Upload all code files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-files
          path: .

  formatting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download code files from artifact
        uses: actions/download-artifact@v4
        with:
          name: code-files

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-deps-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-deps-${{ runner.os }}-

      - name: Run Spring Java Format check
        run: |
          echo "🔍 Checking Spring Java Format..."
          if ! grep -i 'spring-javaformat-maven-plugin' pom.xml; then
            echo "❌ ERROR: Missing Spring Java Format plugin configuration in pom.xml"
            echo "Refer to: https://github.com/spring-io/spring-javaformat"
            exit 1
          fi
          mvn spring-javaformat:validate
          echo "✅ Spring Java Format validation passed!"

  linting:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download code files from artifact
        uses: actions/download-artifact@v4
        with:
          name: code-files

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-deps-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-deps-${{ runner.os }}-

      - name: Run Checkstyle
        run: |
          echo "🔍 Running Checkstyle..."
          if ! grep -i 'maven-checkstyle-plugin' pom.xml; then
            echo "❌ ERROR: Missing Checkstyle plugin configuration in pom.xml"
            echo "Refer to: https://maven.apache.org/plugins/maven-checkstyle-plugin/"
            exit 1
          fi
          if [ ! -f "checkstyle.xml" ]; then
            echo "❌ ERROR: Missing checkstyle.xml configuration file"
            echo "Refer to: https://checkstyle.sourceforge.io/"
            exit 1
          fi
          mvn checkstyle:check || exit $?
      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml

  spotbugs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download code files from artifact
        uses: actions/download-artifact@v4
        with:
          name: code-files

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-deps-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-deps-${{ runner.os }}-

      - name: Run SpotBugs
        run: |
          echo "🔍 Running SpotBugs..."
          if ! grep -i 'spotbugs-maven-plugin' pom.xml; then
            echo "❌ ERROR: Missing SpotBugs plugin configuration in pom.xml"
            echo "Refer to: https://github.com/spotbugs/spotbugs-maven-plugin"
            exit 1
          fi
          mvn spotbugs:check || exit $?
      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: spotbugs-report
          path: target/spotbugsXml.xml

  pmd:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download code files from artifact
        uses: actions/download-artifact@v4
        with:
          name: code-files

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-deps-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-deps-${{ runner.os }}-

      - name: Verify PMD configuration file
        run: |
          if [ ! -f "pmd.xml" ]; then
            echo "ERROR: Missing pmd.xml configuration file in the root directory."
            exit 1
          fi

      - name: Run PMD Analysis
        uses: pmd/pmd-github-action@v1
        with:
          config: './pmd.xml'
          src: './src/main/java'
          format: 'sarif'
          output-file: './target/pmd-report.sarif'

      - name: Display PMD Report
        run: |
          echo "PMD Report Summary:"
          xmllint --format ./target/pmd-report.xml | grep -E 'file|violation' || echo "No violations found."

      - name: Upload PMD Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: './target/pmd-report.xml'

  dependency-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download code files from artifact
        uses: actions/download-artifact@v4
        with:
          name: code-files

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-deps-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-deps-${{ runner.os }}-

      - name: Run OWASP Dependency-Check
        run: |
          echo "🔍 Running OWASP Dependency-Check..."
          if ! grep -i 'dependency-check-maven' pom.xml; then
            echo "❌ ERROR: Missing Dependency-Check plugin configuration in pom.xml"
            echo "Refer to: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/"
            exit 1
          fi
          mvn org.owasp:dependency-check-maven:check || exit $?
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: owasp-dependency-check-report
          path: target/dependency-check-report.html

  coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download code files from artifact
        uses: actions/download-artifact@v4
        with:
          name: code-files

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-deps-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-deps-${{ runner.os }}-

      - name: Run JaCoCo tests and enforce coverage
        run: |
          echo "🔍 Running JaCoCo for code coverage..."
          if ! grep -i 'jacoco-maven-plugin' pom.xml; then
            echo "❌ ERROR: Missing JaCoCo plugin configuration in pom.xml"
            echo "Refer to: https://www.eclemma.org/jacoco/trunk/doc/maven.html"
            exit 1
          fi
          mvn test jacoco:report jacoco:check || exit $?
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html
