on:
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string
      environment:
        required: true
        type: string
      secret_name:
        required: true
        type: string
jobs:
  deploy_infra_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Build compose filename
        id: build-compose-filename
        run: |
          echo "Artifact: ${{ inputs.artifact }}"
          echo "Environment: ${{ inputs.environment }}"
          filename="${{ inputs.artifact }}-compose-${{ inputs.environment }}.yml"
          echo "Generated filename: $filename"
          echo "COMPOSE_FILENAME=$filename" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Transfer Compose File to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_SSH_HOST_PRE }}
          username: ${{ secrets.DO_SSH_USER_PRE }}
          key: ${{ secrets.DO_SSH_KEY_PRE }}
          source: ".github/workflows/infra/docker/${{ env.COMPOSE_FILENAME }}"
          target: /opt/summoners-sync/infra/docker/
          rm: true

      # Deploy Infra
      - name: Deploy Infra
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DO_SSH_HOST_PRE }}
          username: ${{ secrets.DO_SSH_USER_PRE }}
          key: ${{ secrets.DO_SSH_KEY_PRE }}
          script: |
            cd /opt/summoners-sync/infra/docker

            echo "${{ secrets[inputs.secret_name] }}" > .env

            docker-compose --env-file .env -f ${{ env.COMPOSE_FILENAME }} up -d