on:
    workflow_call:
      inputs:
        artifact:
          required: true
          type: string
        environment:
          required: true
          type: string
jobs:
    deploy_infra_artifact:
      runs-on: ubuntu-latest
      steps:
        - name: Build compose filename
          id: build-compose-filename
          run: |
            echo "Artifact: ${{ inputs.artifact }}"
            echo "Environment: ${{ inputs.environment }}"