name: Unified Code Quality

on:
  workflow_call:

jobs:
  detect-language:
    uses: zerodaycode/app-summoners-sync/.github/workflows/detect-language.yml@feature/new-github-actions

  trigger-java-code-quality:
    needs: detect-language
    if: ${{ needs.detect-language.outputs.language == 'Java' }}
    uses: zerodaycode/app-summoners-sync/.github/workflows/code-quality-java.yml@feature/new-github-actions

  fail-on-unsupported-language:
    needs: detect-language
    if: ${{ needs.detect-language.outputs.language != 'Java' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail Workflow for Unsupported Language
        run: |
          echo "Error: Unsupported language detected: ${{ steps.detect-language.outputs.language }}."
          exit 1
