name: Unifies Code Quality

on:
  workflow_call:

jobs:
  detect-and-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Call Detect Main Language workflow
        id: detect_language
        uses: ./.github/workflows/detect-language.yml

      - name: Check if the detected language is Java
        id: check_java
        run: |
          if [[ "${{ steps.detect_language.outputs.language }}" == "Java" ]]; then
            echo "Java detected, triggering Java Maven Code Quality workflow"
            echo "trigger_java=true" >> $GITHUB_ENV
          else
            echo "Language detected is not Java. Skipping Java Maven Code Quality."
            echo "trigger_java=false" >> $GITHUB_ENV

  trigger-java-code-quality:
    if: ${{ env.trigger_java == 'true' }}
    needs: detect-and-trigger
    uses: ./.github/workflows/java-maven-code-quality.yml
